### ISSUE TITLE
Can we have the results with hyperlinks to the page?

### ISSUE THREAD

**Issue by hetong007** [ThomasDelteil/VisualSearch_MXNet#1]
If the latency is too large (if query for each page ), at least we may want to have the title in full length so that users can copy and search.

Or another step further:

1. Add a button to each image to "search in amazon".
2. A search bar on top for users to copy/paste title into it.

**Comment by ThomasDelteil** [comment]
The data is a small subset of the 2013 catalog, I am not sure the ASIN are still available. But we could have a link that might or might not work, I'll add that

**Comment by ThomasDelteil** [comment]
Link to product added on every images
