### ISSUE TITLE
Own Dataset

### ISSUE THREAD

**Issue by visuazn** [ThomasDelteil/VisualSearch_MXNet#12]
Hey, any reference to add our own dataset in this code?

**Comment by ThomasDelteil** [comment]
Effectively you can remove all the download file logic etc, and then you put the prefix of your jpg images for example like this:
```
image_paths = '<HERE GOES YOUR PATH>'
list_files = glob.glob(os.path.join(images_path, '**.jpg'))
```
The only constraint it has is to have all your images in a single folder.

**Comment by visuazn** [comment]
Thanks for that.
how about Creating data files for offline inference?
do i need to work with this same?

**Comment by ThomasDelteil** [comment]
this approach uses KNN search on the deep features of the test image for inference. 
Look at the code here: https://github.com/ThomasDelteil/VisualSearch_MXNet/blob/master/mms/visualservice.py#L42

**Comment by visuazn** [comment]
Cool Thanks. Will check this
