### ISSUE TITLE
Inconsistencies in Predictions

### ISSUE THREAD

**Issue by OElesin** [ThomasDelteil/VisualSearch_MXNet#7]
@ThomasDelteil, thanks for this great tutorial. I have some questions in this regard. I get inconsistent results when the `net` functions is not used on the transformed image array. See below:

1. When the net function is set
```python
p.set_ef(300) # ef should always be > k
image = plt.imread(path)[:,:,:3]
image_t, _ = transform(nd.array(image), 1)
output = net(image_t.expand_dims(axis=0).as_in_context(ctx))
labels, distances = p.knn_query([output.asnumpy().reshape(-1,)], k = 25)
images = [image]
images += [plt.imread(dataset.items[label][0]) for label in labels[0]]
```
<img width="434" alt="screen shot 2019-01-10 at 7 34 40 am" src="https://user-images.githubusercontent.com/11349090/50950746-3274f680-14ab-11e9-9bc5-aaa4b1ebbb08.png">

2. When the net function not is set
```python
p.set_ef(300) # ef should always be > k
image = plt.imread(path)[:,:,:3]
image_t, _ = transform(nd.array(image), 1)
output = image_t.expand_dims(axis=0).as_in_context(ctx)
labels, distances = p.knn_query([output.asnumpy().reshape(-1,)], k = 25)
images = [image]
images += [plt.imread(dataset.items[label][0]) for label in labels[0]]
```
<img width="438" alt="screen shot 2019-01-10 at 7 35 03 am" src="https://user-images.githubusercontent.com/11349090/50950757-3acd3180-14ab-11e9-84a0-c075e7d9c0b4.png">

Looking at the code for the model server, the `net` function is not used and the results from your deployment seems to work fine. However, when I did the same, I got the inconsistent results.

Can you please help explain why this is? 

Thanks in advance

**Comment by ThomasDelteil** [comment]
The `net` function, is the actual CNN. It is used in the `MXNetBaseService` parent class of the service to featurize your image, see https://github.com/awslabs/mxnet-model-server/blob/master/mms/model_service/mxnet_model_service.py#L123
